name: rayfronts
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - pyg
  - robostack-jazzy
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - pip
  - tbb==2021.13
  - libboost
  - ros-jazzy-desktop
  - ros-jazzy-rmw-zenoh-cpp
  - pip:
    - rerun-sdk
    - timm
    - einops
    - open_clip_torch
    - transformers
    - scipy
    - scikit-learn
    - hydra-core
    - nanobind
    - tqdm
    - torch
    - torchvision
    - torch-scatter
